spring.application.name=SpringBootSample

# DataSource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.sql-script-encoding=UTF-8
spring.datasource.initialize=true
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql


# H2DB
spring.h2.console.enabled=true

# message
spring.messages.basename=i18n/messages,i18n/ValidationMessages

# MyBatis
mybatis.mapper-locations=classpath*:mapper/h2/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.domain.kintai.model

# Log Level
logging.level.com.example=debug

# Spring MVC 関連のログ出力（例外処理やコントローラー）
logging.level.org.springframework.web=debug

# エラーハンドリング関連の詳細ログ出力
logging.level.org.springframework.boot.web.servlet.error=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=debug

# 最終的にすべてのログを出力（必要なら）
logging.level.root=debug

# 例外詳細を出力
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.boot.web.servlet=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR

# 例外の詳細なスタックトレースを標準出力
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# ======================================================

# JPA

# ======================================================


## テーブル自動作成
#spring.jpa.hibernate.ddl-auto=none
#
## SQLログ出力
#logging.level.org.hibernate.SQL=debug
#
## バインドパラメーター出力
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
#logging.level.org.hibernate.type.EnumType=trace

spring.main.allow-circular-references=true